### ISSUE TITLE
Game does not start

### ISSUE THREAD

**Issue by DaDiGui** [BounceSMP/BounceStyles#8]
I have installed the latest versions of the mods dependencies for 1.18.2 and in log I get this error, that they are not in the correct version.

arclight-forge-1.18.2-1.0.8
FORGE-40.2.1
LOG COMPLETE: https://mclo.gs/O7o3jmf

[25abr2023 21:53:09.854] [main/ERROR] [net.minecraftforge.fml.loading.ModSorter/LOADING]: Missing or unsupported mandatory dependencies:
	Mod ID: 'geckolib3', Requested by: 'bounce_styles', Expected range: '[3.0.64,)', Actual version: '3.0.57'
	Mod ID: 'architectury', Requested by: 'bounce_styles', Expected range: '[4.11.91,)', Actual version: '4.11.90'

**Comment by RyanV97** [comment]
I seem to have made a mistake with the Geckolib version in the relevant mod metadata files, will be fixed next version.
The Architectury version is accurate though, so you do still need to update that to 4.11.91 (Required due to a fix in the PLAYER_CLONE event)
