### ISSUE TITLE
Mod doesn't load on 1.20.1

### ISSUE THREAD

**Issue by Sadoul** [BounceSMP/BounceStyles#9]
Hi. I don't have a mod running on version 1.20.1. He writes that he needs geckolib of the old version. I don't know what to do. 
[13:46:09] [main/ERROR] [ne.mi.fm.lo.ModSorter/LOADING]: Missing or unsupported mandatory dependencies:
Mod ID: 'geckolib3', Requested by: 'bounce_styles', Expected range: '[3.0.57,)', Actual version: '[MISSING]'
[latest.log](https://github.com/BounceSMP/BounceStyles/files/13458292/latest.log)

**Comment by RyanV97** [comment]
I made an error with the Forge metadata.
I've updated the 2.5.0 Forge jar file, so redownloading BounceStyles should fix this issue.
